version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/wanderlust
      - REDIS_URL=redis://redis:6379
    networks:
      - custom_network
    volumes:
      - ./backend:/app
    # env_file:
    #   - ./backend/.env

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - custom_network
    volumes:
      - mongo-data:/data/db
  
  mongo-seed:
    image: mongo:latest
    depends_on:
      - mongodb
    volumes:
      - ./backend/data:/data
    entrypoint: ["sh", "-c", "mongoimport --host mongodb --db wanderlust --collection posts --file /data/sample_posts.json --jsonArray"]
    networks:
      - custom_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    # environment:
    #   - VITE_API_PATH="http://localhost:5000"
    networks:
      - custom_network
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env

  redis:
    image: redis:latest
    ports:
      - "6378:6379"
    networks:
      - custom_network
    volumes:
      - redis-data:/data

networks:
  custom_network:
    driver: bridge

volumes:
  mongo-data:
  redis-data: